id: P414BEB44
initial_creation_type: input
source_metadata:
  Title: Bodhicaryāvatāra of Śāntideva with the Commentary Panjika of Prajnakaramati
  Editor: Vaidya, P. L.
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1960'
  1 bodhicittānuśaṃso nāma prathamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2 pāpadeśanā nāma dvitīyaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3 bodhicittaparigraho nāma tṛtīyaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4 bodhicittāpramādo nāma caturthaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5 saṃprajanyarakṣaṇaṃ nāma pañcamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  6 kṣāntipāramitā nāma ṣaṣṭhaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  7 vīryapāramitā nāma saptamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  8 dhyānapāramitā nāma aṣṭamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  9 prajñāpāramitā nāma navamaḥ paricchedaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  10 pariṇāmanāparicchedo daśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2005'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:42:02.496885'
last_modified_at: '2022-03-08T16:42:02.496897'
